### ISSUE TITLE
German Compendiums

### ISSUE THREAD

**Issue by Muwak77** [n3dst4/gumshoe-fvtt#640]
I did a bunch of translations for German Compendiums which also include descriptions. As far as i understand, you are working with Pelgran now and maybe there is a way to include them in the System to promote ToC for a german Audience. 

I Also have translated about 60% of the Core-Rules which might be Interesting to them to put in a Module. Maybe you can use this in some way.

**Comment by n3dst4** [comment]
Hey @Muwak77 really sorry, I thought I'd replied but I must not have hit the button.

So, I'm afraid we have legal issues here. non-english versions of Pelgrane products are licenced out to other companies. So either there's a German edition of ToC with a licensee who is not Pelgrane, *or* Pelgrane will not approve a German translation because they want to be able to sell the right to create a German translation in future.

There's also the thing that Pelgrane don't want any *text* made available for free.

I think it's very cool that you've done this, but you've kind of hit the same legal quagmire that I did when I started INVESTIGATOR. I published v1.0 and then got a great big "No" from Foundry, and I had to spend months negotiating with Pelgrane. The 13th Age guys had the exact same thing.

I would suggest that you put together a small private module to make it available for folks who want it, and then maybe talk to Pelgrane about who owns the rights to German ToC.

Also, have you seen https://pelgranepress.com/2023/09/06/announcing-trail-of-cthulhu-2nd-edition/ ? 2nd edition is coming, so they may be able to hook you up with the German publisher - they may be very grateful to have a bunch of work done! (I'm guessing that a lot of the text will be unchanged.)

**Comment by n3dst4** [comment]
I'm going to close this ticket because I'm not in a position to use the content myself, but please reply or give me a shout on Discord if I can help with anything.

**Comment by Muwak77** [comment]
Yea i expected that :) 

As the lazy guy that i am, i was hoping to just give it to you so everbody can profit from it without any more efford on my part. 

But I'll contact them and see where this goes (I'm not really interested in profit and would be happy with free publications or some other kind of appreciation). 

AFAIK the german "publisher" is some online rpg-giftshop who has been advertising TOC for years without ever delivering.

But lets see where this goes.

You have discord: never saw it, can you send men an invite?

**Comment by n3dst4** [comment]
Here's an invite that should take you directly to the Pelgrane server. Most of the INVESTIGATOR chat goes on in the "virtual tabletops" channel: https://discord.gg/eytTpdv6
